version: '3.8'

services:
  auth-service-test:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile.test
    ports:
      - "9081:8081"
    networks:
      - test-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - test-db

  product-service-test:
    build:
      context: ./product-service
      dockerfile: Dockerfile.test
    ports:
      - "9082:8082"
    networks:
      - test-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - test-db

  order-service-test:
    build:
      context: ./order-service
      dockerfile: Dockerfile.test
    ports:
      - "9083:8083"
    networks:
      - test-network
    environment:
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      - test-db

  test-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    networks:
      - test-network

  integration-tests:
    build:
      context: ./integration-tests
      dockerfile: Dockerfile
    networks:
      - test-network
    depends_on:
      - auth-service-test
      - product-service-test
      - order-service-test

networks:
  test-network:
    driver: bridge
