version: '3.8'

services:
  # Application Services
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile.test
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - DB_HOST=auth-db
      - DB_PORT=5432
    depends_on:
      - auth-db
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile.test
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - DB_HOST=product-db
      - DB_PORT=5432
    depends_on:
      - product-db
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile.test
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - DB_HOST=order-db
      - DB_PORT=5432
    depends_on:
      - order-db
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Databases for testing
  auth-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=auth_test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5433:5432"
    networks:
      - test-network
    volumes:
      - auth-test-data:/var/lib/postgresql/data

  product-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=product_test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5434:5432"
    networks:
      - test-network
    volumes:
      - product-test-data:/var/lib/postgresql/data

  order-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=order_test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5435:5432"
    networks:
      - test-network
    volumes:
      - order-test-data:/var/lib/postgresql/data

  # Integration Tests Service
  integration-tests:
    build:
      context: ./integration-tests
      dockerfile: Dockerfile
    depends_on:
      auth-service:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    networks:
      - test-network
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8082
      - ORDER_SERVICE_URL=http://order-service:8083

networks:
  test-network:
    driver: bridge

volumes:
  auth-test-data:
  product-test-data:
  order-test-data: